### ISSUE TITLE
No function to read pixel data from screen

### ISSUE THREAD

**Issue by smalldevices** [waveshare/WSLCD1in8-v0#1]
It would be useful to be able to read the data from a pixel, or group of pixesl, to check for collisions in games e.g. before moving an object to a position, check if there is a particular colour there, and if so, make a collision.

There's some information on reading pixel information here https://www.avrfreaks.net/comment/1725551#comment-1725551

**Comment by hnwangkg-ezio** [comment]
Sure,Thanks for your advice， the next version will add this feature.
