### ISSUE TITLE
micro:bit update 26 October - library no longer works

### ISSUE THREAD

**Issue by emwdx** [waveshare/WSLCD1in8-v0#2]
After the update on October 26th to the MakeCode website, the library no longer functions. The screen on the display stays blank for any code sent to it.

Using the editor at https://makecode.microbit.org/v0, the blocks work as before.

**Comment by waveshare** [comment]
Using https://makecode.microbit.org/v0 can work as before. 
The new version of https://makecode.microbit.org currently has multiple bugs, 
we will update it as soon as possible.
Thanks for your support!

**Comment by TeddyGag** [comment]
As of 12/28/2018 the library still does not work with the latest makecode.microbit.org

**Comment by waveshare** [comment]
The package has been updated. Please check it: https://github.com/waveshare/WSLCD1in8
